TensorFlow installation not found - running with reduced feature set.

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

Traceback (most recent call last):
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/tensorboard/main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/tensorboard/program.py", line 276, in main
    return runner(self.flags) or 0
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/tensorboard/program.py", line 292, in _run_serve_subcommand
    server = self._make_server()
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/tensorboard/program.py", line 467, in _make_server
    app = application.TensorBoardWSGIApp(
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/tensorboard/backend/application.py", line 139, in TensorBoardWSGIApp
    return TensorBoardWSGI(
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/tensorboard/backend/application.py", line 252, in __init__
    raise ValueError(
ValueError: Duplicate plugins for name projector
TensorFlow installation not found - running with reduced feature set.

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

Traceback (most recent call last):
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/tensorboard/main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/tensorboard/program.py", line 276, in main
    return runner(self.flags) or 0
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/tensorboard/program.py", line 292, in _run_serve_subcommand
    server = self._make_server()
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/tensorboard/program.py", line 467, in _make_server
    app = application.TensorBoardWSGIApp(
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/tensorboard/backend/application.py", line 139, in TensorBoardWSGIApp
    return TensorBoardWSGI(
  File "/data/jixinlong/jixinlong/anaconda3/envs/control/lib/python3.8/site-packages/tensorboard/backend/application.py", line 252, in __init__
    raise ValueError(
ValueError: Duplicate plugins for name projector
